class question:
    
    def questionnage(self):

        
        self.question = [["la voiture est rouge"],
            ['le crayon est vert et sur la table rouge'],
            ['le crayon est vert'],
            ['le crayon est vert et sur la table rouge'],
            ['le crayon est vert et sur la table rouge'],
            ['le crayon est vert et sur la table rouge'],
            ['le crayon est vert et sur la table rouge'],
            ['le crayon est vert et sur la table rouge'],
            ['le crayon est vert et sur la table rouge'],
            ['le crayon est vert et sur la table rouge'],
            ['le crayon est vert et sur la table rouge'],
            ['le crayon était'],
            ['était'],
            ['le crayon est vert et sur la table rouge'],
            ['le crayon est vert et sur la table rouge'],
            ['le crayon est vert et sur la table rouge'],
            ['le crayon est vert et sur la table rouge'],
            ['le crayon est vert et sur la table rouge'],
            ['le crayon est vert et sur la table rouge'],
            ['le crayon est vert et sur la table rouge'],
            ['le crayon est vert et sur la table rouge'],
            ['le crayon est vert et sur la table rouge'],
            ['le chat était roux'],
            ['le crayon est vert et sur la table rouge'],
            ['le chat était roux'],
            ['le est bleu'],
            ['le jean est bleu'],
            ['le jean est bleu'],
            ['le jean était bleu'],
            ['le jean est bleu'],
            ['le jean est bleu'],
            ['le jean est bleu'],
            ['le jean bleu'],
            ['le jean bleu'],
            ['le jean bleu'],
            ['le jean bleu'],
            ['le jean bleu'],
            ['le jean bleu'],
            ['le jean bleu'],
            ['le jean bleu'],
            ['le jean bleu'],
            ['le jean est bleu'],
            ['le jean bleu'],
            ['le jean est bleu'],
            ['le jean bleu'],
            ['le jean bleu'],
            ['le jean bleu'],
            ['le jean bleu'],
            ['le jean bleu'],
            ['le jean bleu'],
            ['le jean bleu'],
            ['le jean bleu et le crayon vert'],
            ['le crayon vert'],
            ['le jean bleu'],
            ['le jean bleu'],
            ['le jean bleu'],
            ['le jean bleu'],
            ['le jean bleu'],
            ['le jean bleu'],
            ['le jean bleu est sur la chaise'],
            ['le jean bleu est sur la chaise'],
            ['le jean bleu est sur la chaise'],
            ['le jean bleu est sur la chaise'],
            ['le jean'],
            ['le jean'],
            ['le jean'],
            ['le jean'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull'],
            ['le jean à droite du pull bleu'],
            ['le jean bleu à droite du pull rouge'],
            ['le jean bleu à droite du pull rouge'],
            ['le jean bleu à droite du pull rouge'],
            ['le jean bleu à droite du pull rouge'],
            ['le jean bleu à droite du pull rouge'],
            ['le jean bleu à droite du pull rouge'],
            ['le jean bleu'],
            ['le jean bleu à droite du pull rouge'],
            ['le jean bleu à droite du pull rouge'],
            ['le jean bleu à droite du pull rouge'],
            ['le jean bleu à droite du pull rouge'],
            ['le jean bleu à droite du pull rouge'],
            ['le jean bleu à droite du pull rouge'],
            ['le jean bleu à gauche du pull rouge'],
            ['le jean bleu à gauche du pull rouge'],
            ['le jean bleu à gauche du pull rouge'],
            ['le jean bleu à gauche du pull rouge'],
            ['le jean bleu à gauche du pull rouge'],
            ['le jean bleu à gauche du pull rouge'],
            ['le jean bleu à gauche du pull rouge'],
            ['le jean bleu à gauche du pull rouge'],
            ['le jean bleu à gauche du pull rouge'],
            ['le jean bleu à gauche du pull rouge'],
            ['le jean bleu à gauche du pull rouge'],
            ['la'],
            ['la'],
            ['la'],
            ['la'],
            ['la'],
            ['la'],
            ['la'],
            ['la'],
            ['la'],
            ['la'],
            ['la'],
            ['la'],
            ['la'],
            ['la'],
            ['la'],
            ['la'],
            ['la'],
            ['la'],
            ['la'],
            ['la'],
            ['la'],
            ['la'],
            ['la'],
            ['la'],
            ['la'],
            ['la voiture'],
            ['la voiture'],
            ['la'],
            ['gauche'],
            ['gauche'],
            ['gauche'],
            ['gauche'],
            ['gauche'],
            ['gauche'],
            ['gauche'],
            ['gauche droite gauche'],
            ['gauche droite gauche'],
            ['gauche droite'],
            ['gauche droite bas'],
            ['gauche bas droite'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['le pull est rouge et la mer est bleu'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['le jean bleu à gauche du pull rouge'],
            [' jean bleu à gauche du pull rouge'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas droite gauche bas droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['self.liste_direction'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['droite gauche bas'],
            ['le jean bleu à gauche du pull rouge'],
            ['le jean bleu à gauche du pull rouge'],
            ['le jean bleu à gauche du pull rouge'],
            ['le jean bleu en haut du pull rouge'],
            ['le jean bleu en haut du pull rouge'],
            ['le jean bleu en haut du pull rouge'],
            ['le jean bleu en bas du pull rouge'],
            ['le jean bleu à droite du pull rouge'],
            ['le jean bleu à droite du pull rouge'],
            ['le jean bleu à gauche du pull rouge'],
            ['le chien noir est à droite du chat roux'],
            ['la voiture jaune'],
            ['le chien noir est à droite du chat roux'],
            ['la voiture roule'],
            ['la voiture roule'],
            ['la voiture roule'],
            ['la voiture roule'],
            ['la voiture roule'],
            ['la voiture roule'],
            ['le chien'],
            ['le chien et le chat'],
            ['le chien noir'],
            ['le chien noir'],
            ['le chien noir'],
            ['le chien noir'],
            ['le chien noir'],
            ['le chien noir'],
            ['le chien noir'],
            ['le chien noir'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat noir'],
            ['chien'],
            ['chien'],
            ['chien'],
            ['chien'],
            ['chien noir'],
            ['le chien noir'],
            ['chien noir'],
            ['le chien noir'],
            ['le chien noir'],
            ['le chien est noir'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir le chien noir'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['e chien noir est à droite du chat roux'] ]