class question:
    
    def questionnage(self):

        
        self.question = [["la voiture est rouge"],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le jean noir est bleu'],
            ['le jean noir est bleu'],
            ['le jean noir est bleu'],
            ['le jean noir est bleu'],
            ['le jean noir est bleu'],
            ['le jean noir est bleu'],
            ['le jean noir est bleu'],
            ['le jean noir'],
            ['le jean noir'],
            ['le jean noir'],
            ['le jean noir'],
            ['le jean noir'],
            ['le jean noir'],
            ['le jean noir'],
            ['le jean noir'],
            ['le jean noir'],
            ['le jean noir'],
            ['le jean noir'],
            ['le jean noir'],
            ['le chien noir est à droite du chat roux'],
            ['jean boit du thé'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert.'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le  crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['la voiture à gauche du chat'],
            ['la voiture à gauche du chat'],
            ['la voiture à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['la voiture à gauche du chat'],
            ['la voiture à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien à gauche du chat'],
            ['la voiture à gauche du chat'],
            ['la voiture à gauche du chat'],
            ['la voiture à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le crayon vert'],
            ['le chien rouge'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chatle chien était à gauche du chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien'],
            ['le chien '],
            ['le chien et le chat'],
            ['chien'],
            ['chien'],
            ['chien'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['chien'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['avion'],
            ['avion'],
            ['avio'],
            ['avion'],
            ['avion'],
            ['avion'],
            ['avion'],
            ['avion'],
            ['avion'],
            ['avion'],
            ['chien'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien à gauche du chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['requin'],
            ['le chien et le chat, ils vont à la piscine'],
            ['chat'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat ils vont à la piscine'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['.'],
            ['.'],
            ['.'],
            ['.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat'],
            ['le chien'],
            ['le chien'],
            ['le chien'],
            ['le chien'],
            ['le chien'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['ils'],
            ['ils'],
            ['ils'],
            ['ils'],
            ['je tu il'],
            ['ils'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien il'],
            ['le chien il'],
            ['le chien il'],
            ['le chien il'],
            ['le chien il'],
            ['chien il'],
            ['le chien il'],
            ['chat chien ils'],
            ['chien chat ils'],
            ['chat chien ils'],
            ['chat chien ils'],
            ['chat chien ils'],
            ['chat il'],
            ['chat chien ils'],
            ['chat chien ils'],
            ['chat chien ils'],
            ['chat chien ils'],
            ['chat chien ils'],
            ['le chien ce dernier'],
            ['le chien ce dernier'],
            ['le chien ce dernier'],
            ['le chien ce dernier'],
            ['chien ce dernier'],
            ['le chien ce dernier, il'],
            ['le chien ce dernier, il'],
            ['le chien ce dernier, il'],
            ['le chien ce dernier, il'],
            ['le chien ce dernier, il'],
            ['le chien ce dernier, il'],
            ['le chien ce dernier, il'],
            ['le chien ce dernier, il'],
            ['le chien ce dernier, il'],
            ['le chien ce dernier, il'],
            ['le chien ce dernier, il'],
            ['le chien et le chat, ils '],
            ['le chien et le chat, ils'],
            ['le chien et le chat, ils'],
            ['le chien et le chat, ils'],
            ['le chien et le chat, ils'],
            ['chien il'],
            ['le chien et le chat, ils'],
            ['chien chat ils'],
            ['le chien et le chat, ils'],
            ['le chien et le chat, ils'],
            ['chien chat ils'],
            ['chat il'],
            ['le chien ce dernier'],
            ['le chien ce dernier'],
            ['ce dernier'],
            ['ce dernier'],
            ['chien ce dernier,'],
            ['ce dernier'],
            ['chien ce dernier'],
            ['ce dernier'],
            ['chien ce dernier'],
            [' ce dernier'],
            ['ce dernier'],
            ['ce dernier'],
            ['ce dernier, il'],
            ['le chat, le chien ce dernier, il'],
            ['le chat, le chien, ce dernier il'],
            ['le chat, le chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['le chien ce dernier, il'],
            ['chat chien, ce dernier il'],
            ['le chien ce dernier, il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, le dernier il'],
            ['chien'],
            ['chien'],
            ['chat chien, le dernier il'],
            ['chat chien, le dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['le requin et le dauphin'],
            ['le requin et le dauphin'],
            ['le chien était à gauche du chat'],
            ['le requin et le dauphin'],
            ['le chien était à gauche du chat'],
            ['le requin et le dauphin'],
            ['le requin et le dauphin'],
            ['le requin et le dauphin vont au intermarché'],
            ['le requin et le dauphin vont au marché'],
            ['le requin et le dauphin vont au marché'],
            ['le requin et le dauphin vont au marché'],
            ['chien chat marché'],
            ['chien et chat dinosaure'],
            ['chat et chien dinosaure'],
            ['chat et chien dinosaure'],
            ['chat et chien dinosaure'],
            ['chat et chien dinosaure'],
            ['chat et chien dinosaure requin'],
            ['chat et chien bite et gateau'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il aime les amandes'],
            ['le chat, il'],
            ['le chat, il'],
            ['le chat, il'],
            ['le chat, il'],
            ['le chat il elle'],
            ['le chat il'],
            ['le chat il'],
            ['le chat il'],
            ['le chat il'],
            ['le chat il'],
            ['chat il'],
            ['chat il'],
            ['chat, il'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['cjat'],
            ['za'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat et le chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chien et cjat'],
            ['chat et chien, dinosaure et lampe'],
            ['le chat'],
            ['le chat.'],
            ['chat.'],
            ['chat'],
            ['cjat'],
            ['chat'],
            ['le chat.'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat.'],
            ['le chat'],
            ['le chat.'],
            ['le chat'],
            ['le chat'],
            ['le chat.'],
            ['le chat'],
            ['chat'],
            ['le chat'],
            ['le chat.'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat. le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat. le chat'],
            ['le chat.'],
            ['le chat'],
            ['le chat.'],
            ['le chat. le chat'],
            ['le chat'],
            ['le chat. le chat'],
            ['le chat'],
            ['le chat.'],
            ['le chat'],
            ['le chat'],
            ['le chat.'],
            ['le chat'],
            ['le chat.'],
            ['le chat.'],
            ['le chat. le'],
            ['le chat. le chat. le'],
            ['le chat.'],
            ['le chat.'],
            ['le chat.'],
            ['le chat.'],
            ['le chat'],
            ['le chat'],
            ['le chat.'],
            ['le chat'],
            ['le chat.'],
            ['le chat. le chat.'],
            ['le chat. le'],
            ['le chat. le'],
            ['le chat.'],
            ['le chat'],
            ['le chat.'],
            ['le chat.'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat.le'],
            ['le chat. le'],
            ['le chat.le'],
            ['le chat. le chat. le'],
            ['le chat'],
            ['le chat. le chat'],
            ['le chat. le chat.'],
            ['le chat. le chat'],
            ['le chat. le chat.'],
            ['le chat. le chat'],
            ['le chat. le chat.'],
            ['le chat.'],
            ['le chat. le chat'],
            ['le chat. le chat.'],
            ['le chat.'],
            ['le chat.'],
            ['le chat.'],
            ['le chat'],
            ['le chat.'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat. le chat'],
            ['le chat. le chat'],
            ['le chat. le chat'],
            ['le chat.'],
            ['le chat'],
            ['le chat. le'],
            ['le chat. le'],
            ['le chat.'],
            ['le chat. le'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat.'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le chat. le'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le'],
            ['le'],
            ['le chat. le'],
            ['le chat. le'],
            ['le chat. le'],
            ['le chat. le'],
            ['le chat'],
            ['le'],
            ['le'],
            ['le'],
            ['le.'],
            ['le chat. le'],
            ['le chat'],
            ['le chat. le. le chat'],
            ['le'],
            ['le'],
            ['le. le'],
            ['le'],
            ['le. le'],
            ['le chat le chien. et le toutout'],
            ['le chat et le chien. le mec'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le'],
            ['le chat'],
            ['le chat'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le'],
            ['le chat. le chat. le'],
            ['le'],
            ['le chat'],
            ['le'],
            ['le chat'],
            ['le chat'],
            ['le'],
            ['le'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat. le'],
            ['le chat. le'],
            ['le chat. le'],
            ['le chat.'],
            ['le '],
            ['le chat'],
            ['le'],
            ['le chat.'],
            ['le'],
            ['le chat. le'],
            ['le chat'],
            ['le chat. le'],
            ['le chat. le'],
            ['le chat.'],
            ['le chat. le chat'],
            ['le chat. le chat. le'],
            ['le chat et le chien'],
            ['le. le chat.'],
            ['le chat.'],
            ['le chat était'],
            ['était'],
            ['était'],
            ['était.'],
            ['était.'],
            ['était.'],
            ['était.'],
            ['était.'],
            ['était.'],
            ['était.'],
            ['était.'],
            ['était.'],
            ['était'],
            ['était'],
            ['était.'],
            ['était.'],
            ['était.'],
            ['était.'],
            ['le chat était'],
            ['le chat était'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat et le chien'],
            ['le chien et le chat'],
            ['chien chat le la dinosaure voiture'],
            ['chien le chat'],
            ['chat le'],
            ['chat le'],
            ['avion chat'],
            ['avion chat'],
            ['avion chat'],
            ['avion chat'],
            ['avion chat'],
            ['avion chat'],
            ['avion chat'],
            ['avion chat'],
            ['avion chat'],
            ['avion chat chat avion'],
            ['avion chat'],
            ['avion chat'],
            ['avion chat'],
            ['chat chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chien gauche chat. chien et chat'],
            ['chien à gauche chat. chien et chat'],
            ['chien et chat. chien à droite chat'],
            ['le. chat'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat le. chien'],
            ['chat. le chien'],
            ['chat. requin'],
            ['requin. chat'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien. chat'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chaussure. tissu'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['les con sont gentils. les chiens aussi'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat et le chien. Ils sont copains'],
            ['le chat. chien'],
            ['le chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat'],
            ['chat. chien'],
            ['le chat. chien'],
            ['chien. chat'],
            ['le chien aime les chat. chat'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chaussure. lampe'],
            ['chien. chat'],
            ['chat. chien'],
            ['chat.'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat.'],
            ['chat. le'],
            ['chat.'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chien. chat'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien. le chat'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chien. chat'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['lampe. chaussure'],
            ['chat. chien'],
            ['chat. chient'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chien droite chat'],
            ['chien à droite du chien'],
            ['le chien gauche chat'],
            ['chien gauche chat'],
            ['chat gauche chien'],
            ['chat gauche chien'],
            ['chat gauche chien'],
            ['char gauche chien'],
            ['chat gauche chien'],
            ['chat gauche chien'],
            ['chat gauche chien'],
            ['gauche'],
            ['gauche'],
            ['gauche'],
            ['chien gauche chat'],
            ['chat et chien'],
            ['est'],
            ['suis'],
            ['était'],
            ['était'],
            ['chat gauche chien'],
            ['chien était a gauche du chat'],
            ['chat'],
            ['chien'],
            ['chat'],
            ['chien gauche voiture'],
            ['chat a gauche chien'],
            ['chat gauche chien'],
            ['chien était gauche chat'],
            ['chien était'],
            ['était'],
            ['chien était gauche chat'],
            ['chien chat'],
            ['le chat et le chien. Ils sont copains'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['chat. chien'],
            ['chat. chien'],
            ['le chat et le chien. Ils sont copains'],
            ['chat et chien. Copain'],
            ['chat chien. copain'],
            ['chat et chien. copain'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['crocodile et lapin'],
            ['chat et oiseau'],
            ['oiseau et lapin'],
            ['lapin et chat était'],
            ['le chat et lapin était. chaussure'],
            ['chat et chien. chaussure'],
            ['chat et chien. chaussure'],
            ['chat et chien. chaussue'],
            ['chat.'],
            ['chat.'],
            ['chat et chien. chat'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chien. chat'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['chat. chien'],
            ['le chat et lapin était. chaussure'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['chat chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chien'],
            ['oiseau a gauche chat'],
            ['chien'],
            ['le chat et lapin était. chaussure'],
            ['était fu'],
            ['etait etait'],
            ['étais était'],
            ['le chien et le chat. le mamouth et le singe'],
            ['le chien et le chat. le livre et le singe'],
            ['chien'],
            ['le verre. Il boit'],
            ['le verre. Il boit'],
            ['le verre. Il boit'],
            ['le chat et lapin était. chaussure'],
            ['le chat boit'],
            ['le chat boit'],
            ['le chat boit'],
            ['le chat boit'],
            ['le chat boit'],
            ['chat boit'],
            ['chat boit'],
            ['chat boit'],
            ['chat. boit'],
            ['chat boit'],
            ['CHAT BOIT'],
            ['le chat. il boit'],
            ['chat. boit'],
            ['chat. boit'],
            ['chat. boit'],
            ['chat. boit'],
            ['chat boit'],
            ['chat boit'],
            ['chat boit'],
            ['chat boit'],
            ['chat boit'],
            ['le chat. il boit'],
            ['chat. boit'],
            ['chat lapin. chaussure'],
            ['chat. boit'],
            ['chat. chaussure'],
            ['chat et chaussure. lapin'],
            ['chat. boit'],
            ['chat. lapin boit'],
            ['chat lapin. lapin'],
            ['chat. il boit'],
            ['chat. lapin boit'],
            ['chat. lapin boit'],
            ['chat. lapin'],
            ['chat et lapin. chaussure'],
            ['chat. lapin'],
            ['chat. boit'],
            ['chat. bois'],
            ['chat. lapin'],
            ['chat. lapin'],
            ['chat. lapin'],
            ['chat. lapin'],
            ['chat. boit'],
            ['chat. boit'],
            ['chat. boit'],
            ['chat. boit'],
            ['boit'],
            ['boit'],
            ['boit'],
            ['boit'],
            ['chat. boit'],
            ['chat. boit'],
            ['chat. boit'],
            ['chat. boit'],
            ['chat. boit'],
            ['chat. boit'],
            ['boit'],
            ['chat. Il'],
            ['le chat il'],
            ['le chat. Il'],
            ['chat. il'],
            ['chat. Il'],
            ['chat chien. Il'],
            ['le chat mange une banane'],
            ['chat mange banane'],
            ['le chat mange une banane'],
            ['le chat mange une banane'],
            ['le chat mange une carotte'],
            ['chat mange une carotte'],
            ['chat mange une carotte'],
            ['chat et chien mangent carotte'],
            ['chat chien mangent carotte'],
            ['chat chien mangent carotte'],
            ['chat chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat chien'],
            ['chat chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat et chien'],
            ['chat chien'],
            ['le chat aime les singes'],
            ['le chat aime les singes'],
            ['le chat aime les singes'],
            ['chat'],
            ['le chat aime les singes'],
            ['chat'],
            ['le chat'],
            ['le chat mange le chien'],
            ['le chat mange le chien'],
            ['chat'],
            ['le chat mange'],
            ['le chat mange'],
            ['le chat mange'],
            ['le chat mange '],
            ['le chat mange'],
            ['le chat mange'],
            ['le crocodile mange'],
            ['le chat'],
            ['le chat mange'],
            ['le chat mange'],
            ['le chien mange'],
            ['le chat mange'],
            ['le chat mange'],
            ['le chat mange'],
            ['chat'],
            ['chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le jean'],
            ['la voiture'],
            ['la voiture'],
            ['le chat mange le chien'],
            ['le chat mange le chien'],
            ['le chat mange le chien'],
            ['le chat mange le chien'],
            ['le chat'],
            ['chien'],
            ['le chat'],
            ['le chien'],
            ['le chien'],
            ['le chat mange le chien'],
            ['le chat mange le chien'],
            ['le chat'],
            ['le chat'],
            ['le'],
            ['le chat mange le chien'],
            ['le chat mange le chien'],
            ['le chat mange le chien'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['panda'],
            ['panda'],
            ['panda'],
            ['panda'],
            ['panda'],
            ['panda'],
            ['panda'],
            ['panda'],
            ['le panda'],
            ['le panda'],
            ['le panda'],
            ['le panda'],
            ['le panda'],
            ['le panda'],
            ['le panda'],
            ['le panda. Il pete'],
            ['le panda'],
            ['le panda'],
            ['le panda'],
            ['le panda'],
            ['le panda. pete'],
            ['le panda'],
            ['le panda'],
            ['le panda'],
            ['le panda'],
            ['le panda'],
            ['le panda'],
            ['le panda'],
            ['le panda'],
            ['le panda'],
            ['le panda'],
            ['le panda'],
            ['le panda'],
            ['le panda'],
            ['le panda'],
            ['le panda'],
            ['le panda'],
            ['le panda'],
            ['le panda'],
            ['le panda'],
            ['panda'],
            ['panda'],
            ['chat'],
            ['le chat'],
            ['panda'],
            ['chat'],
            ['le chat'],
            ['chat'],
            ['le panda'],
            ['panda'],
            ['le'],
            ['le'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le chat'],
            ['le '],
            ['le chat'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['lapin'],
            ['le chat mange le chien'],
            ['le chat mange. yo. lu'],
            ['chat mange'],
            ['chat.lapin'],
            ['chat. lapin'],
            ['l. a. p'],
            ['a. p'],
            ['le chat mange le chien'],
            ['le chat mange le chien'],
            ['le chat mange le chien'],
            ['le chat mange le chien'],
            ['la chaussure et le didon. Ils boivent'],
            ['le chat mange le chien'],
            ['le chat mange le chien'],
            ['le chat mange le chien'],
            ['les chien bouffent le chat'],
            ['avion'] ]