class vivant:

    def vivant(self):
        self.vivant_eau = ["poisson",
            "baleine",
            "chien",
            "chat",
            "chien",
            "chat",
            "chien",
            "chien",
            "chat",
            "chien",
            "chat",
            "chien",
            "chat",
            "chien",
            "chien",
            "chien",
            "chat",
            "chien",
            "chien",
            "chien",
            "chat",
            "chien",
            "chien",
            "chien",
            "chat",
            "chat",
            "chat",
            "chat",
            "requin",
            "requin",
            "requin",
            "requin",
            "requin",
            "requin",
            "requin" ]