class question:
    
    def questionnage(self):

        
        self.question = [["la voiture est rouge"],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le chien noir est à droite du chat roux'],
            ['le jean noir est bleu'],
            ['le jean noir est bleu'],
            ['le jean noir est bleu'],
            ['le jean noir est bleu'],
            ['le jean noir est bleu'],
            ['le jean noir est bleu'],
            ['le jean noir est bleu'],
            ['le jean noir'],
            ['le jean noir'],
            ['le jean noir'],
            ['le jean noir'],
            ['le jean noir'],
            ['le jean noir'],
            ['le jean noir'],
            ['le jean noir'],
            ['le jean noir'],
            ['le jean noir'],
            ['le jean noir'],
            ['le jean noir'],
            ['le chien noir est à droite du chat roux'],
            ['jean boit du thé'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert.'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le  crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le crayon vert'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['la voiture à gauche du chat'],
            ['la voiture à gauche du chat'],
            ['la voiture à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien à gauche du chat'],
            ['la voiture à gauche du chat'],
            ['la voiture à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien à gauche du chat'],
            ['la voiture à gauche du chat'],
            ['la voiture à gauche du chat'],
            ['la voiture à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le chien était à gauche du chat'],
            ['le crayon vert'],
            ['le chien rouge'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chatle chien était à gauche du chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien'],
            ['le chien '],
            ['le chien et le chat'],
            ['chien'],
            ['chien'],
            ['chien'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['chien'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['chat'],
            ['avion'],
            ['avion'],
            ['avio'],
            ['avion'],
            ['avion'],
            ['avion'],
            ['avion'],
            ['avion'],
            ['avion'],
            ['avion'],
            ['chien'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien à gauche du chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['requin'],
            ['le chien et le chat, ils vont à la piscine'],
            ['chat'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat ils vont à la piscine'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['.'],
            ['.'],
            ['.'],
            ['.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat'],
            ['le chien'],
            ['le chien'],
            ['le chien'],
            ['le chien'],
            ['le chien'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['ils'],
            ['ils'],
            ['ils'],
            ['ils'],
            ['je tu il'],
            ['ils'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien et le chat, ils vont à la piscine.'],
            ['le chien il'],
            ['le chien il'],
            ['le chien il'],
            ['le chien il'],
            ['le chien il'],
            ['chien il'],
            ['le chien il'],
            ['chat chien ils'],
            ['chien chat ils'],
            ['chat chien ils'],
            ['chat chien ils'],
            ['chat chien ils'],
            ['chat il'],
            ['chat chien ils'],
            ['chat chien ils'],
            ['chat chien ils'],
            ['chat chien ils'],
            ['chat chien ils'],
            ['le chien ce dernier'],
            ['le chien ce dernier'],
            ['le chien ce dernier'],
            ['le chien ce dernier'],
            ['chien ce dernier'],
            ['le chien ce dernier, il'],
            ['le chien ce dernier, il'],
            ['le chien ce dernier, il'],
            ['le chien ce dernier, il'],
            ['le chien ce dernier, il'],
            ['le chien ce dernier, il'],
            ['le chien ce dernier, il'],
            ['le chien ce dernier, il'],
            ['le chien ce dernier, il'],
            ['le chien ce dernier, il'],
            ['le chien ce dernier, il'],
            ['le chien et le chat, ils '],
            ['le chien et le chat, ils'],
            ['le chien et le chat, ils'],
            ['le chien et le chat, ils'],
            ['le chien et le chat, ils'],
            ['chien il'],
            ['le chien et le chat, ils'],
            ['chien chat ils'],
            ['le chien et le chat, ils'],
            ['le chien et le chat, ils'],
            ['chien chat ils'],
            ['chat il'],
            ['le chien ce dernier'],
            ['le chien ce dernier'],
            ['ce dernier'],
            ['ce dernier'],
            ['chien ce dernier,'],
            ['ce dernier'],
            ['chien ce dernier'],
            ['ce dernier'],
            ['chien ce dernier'],
            [' ce dernier'],
            ['ce dernier'],
            ['ce dernier'],
            ['ce dernier, il'],
            ['le chat, le chien ce dernier, il'],
            ['le chat, le chien, ce dernier il'],
            ['le chat, le chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['le chien ce dernier, il'],
            ['chat chien, ce dernier il'],
            ['le chien ce dernier, il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, le dernier il'],
            ['chien'],
            ['chien'],
            ['chat chien, le dernier il'],
            ['chat chien, le dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['chat chien, ce dernier il'],
            ['le requin et le dauphin'],
            ['le requin et le dauphin'],
            ['le chien était à gauche du chat'],
            ['le requin et le dauphin'],
            ['le chien était à gauche du chat'],
            ['le requin et le dauphin'],
            ['le requin et le dauphin'],
            ['le requin et le dauphin vont au intermarché'],
            ['le requin et le dauphin vont au marché'],
            ['le requin et le dauphin vont au marché'],
            ['le requin et le dauphin vont au marché'],
            ['chien chat marché'],
            ['chien et chat dinosaure'],
            ['chat et chien dinosaure'],
            ['chat et chien dinosaure'],
            ['chat et chien dinosaure'],
            ['chat et chien dinosaure'],
            ['chat et chien dinosaure requin'],
            ['chat et chien bite et gateau'] ]